'use client';
import {useEffect,useMemo,useState} from 'react';
type God={id:string;zh:string;en:string;indic:string;gender:'男神'|'女神';role:string;stats:[number,number,number,number]};
const gods:God[]=[
['shiva','湿婆','Śiva','शिव','男神','转化与瑜伽',[88,95,92,72]],['vishnu','毗湿奴','Viṣṇu','विष्णु','男神','秩序与守护',[86,98,82,91]],['brahma','梵天','Brahmā','ब्रह्मा','男神','创造与知识',[97,76,58,82]],['devi','提毗／沙克蒂','Devī / Śakti','देवी','女神','宇宙能量',[86,94,96,90]],['ganesha','象头神','Gaṇeśa','गणेश','男神','智慧与除障',[96,89,70,92]],['lakshmi','吉祥天女','Lakṣmī','लक्ष्मी','女神','福运与丰饶',[82,93,62,98]],['saraswati','辩才天女','Sarasvatī','सरस्वती','女神','知识与艺术',[99,74,52,88]],['durga','杜尔迦','Durgā','दुर्गा','女神','守护与胜利',[81,96,99,85]],['krishna','黑天','Kṛṣṇa','कृष्ण','男神','喜悦与神圣导师',[95,91,84,99]],['rama','罗摩','Rāma','राम','男神','正法与理想王者',[88,96,91,87]],['hanuman','哈奴曼','Hanumān','हनुमान','男神','力量与奉爱',[79,94,98,96]],['kali','迦梨','Kālī','काली','女神','时间与解脱',[84,90,100,74]],['parvati','帕尔瓦蒂','Pārvatī','पार्वती','女神','爱、家庭与修行',[90,91,78,99]],['radha','罗陀','Rādhā','राधा','女神','奉爱与灵魂渴望',[88,78,60,100]],['sita','悉多','Sītā','सीता','女神','大地与坚韧',[84,93,86,97]],['kartikeya','室建陀／穆鲁甘','Skanda / Murugan','स्कन्द','男神','战争与青春',[76,89,99,76]],['jagannath','札格纳特','Jagannātha','जगन्नाथ','男神','世界之主',[83,95,73,94]],['surya','苏利耶','Sūrya','सूर्य','男神','太阳与生命力',[82,91,94,80]],['indra','因陀罗','Indra','इन्द्र','男神','雷雨与天界',[72,84,95,68]],['agni','阿耆尼','Agni','अग्नि','男神','祭火与使者',[79,87,93,78]],['yama','阎摩','Yama','यम','男神','死亡与审判',[91,92,88,70]],['dhanvantari','檀凡陀利','Dhanvantari','धन्वन्तरि','男神','医学与疗愈',[94,93,57,96]],['venkateswara','文卡泰斯瓦拉','Veṅkaṭeśvara','वेंकटेश्वर','男神','恩典与扶持',[85,97,76,94]],['ayyappa','阿耶帕','Ayyappa','അയ്യപ്പൻ','男神','纪律与和合',[87,91,92,88]]
].map(x=>({id:x[0],zh:x[1],en:x[2],indic:x[3],gender:x[4],role:x[5],stats:x[6]} as God));
const modes=[['智慧','洞察、知识与判断',0],['守护','维持秩序与保护众生',1],['勇武','行动、毅力与战斗象征',2],['慈爱','奉爱、疗愈与亲和',3]] as const;
export default function Collection(){
 const[saved,setSaved]=useState<string[]>([]),[left,setLeft]=useState(''),[right,setRight]=useState(''),[mode,setMode]=useState(0),[result,setResult]=useState('');
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem('deity-collection')||'[]'))}catch{}},[]);
 const toggle=(id:string)=>setSaved(prev=>{const n=prev.includes(id)?prev.filter(x=>x!==id):[...prev,id];localStorage.setItem('deity-collection',JSON.stringify(n));return n});
 const owned=useMemo(()=>gods.filter(g=>saved.includes(g.id)),[saved]);
 const fight=()=>{const a=gods.find(g=>g.id===left),b=gods.find(g=>g.id===right);if(!a||!b||a===b){setResult('请选择两位不同的已收藏神祇。');return}const m=modes[mode],av=a.stats[m[2]],bv=b.stats[m[2]],winner=av===bv?null:av>bv?a:b;setResult(winner?`${m[0]}试炼：${winner.zh}更占优势（${av} : ${bv}）。这是象征属性的趣味比较，不代表宗教地位高低。`:`${m[0]}试炼：双方平局（${av} : ${bv}）。两位神祇以不同方式体现同等力量。`)};
 return <main className="collection-page"><nav className="collection-nav"><a href="/">← 神谱</a><b>众神收藏册</b><a href="/relations">关系图 →</a></nav><header><p>DEITY COLLECTION · 本机保存</p><h1>收集众神，<br/><i>开启象征试炼</i></h1><div className="collection-count"><b>{saved.length}</b><span>/ {gods.length}<small>已收藏</small></span></div></header><section className="arena"><div className="arena-copy"><span>众神竞技场</span><h2>选择两位神祇 PK</h2><p>竞技场比较的是故事中的象征属性，而不是判断哪位神“更高级”。每种赛场都会产生不同结果。</p></div><div className="arena-controls"><label>左方<select value={left} onChange={e=>{setLeft(e.target.value);setResult('')}}><option value="">选择已收藏神祇</option>{owned.map(g=><option key={g.id} value={g.id}>{g.zh} · {g.en}</option>)}</select></label><b>VS</b><label>右方<select value={right} onChange={e=>{setRight(e.target.value);setResult('')}}><option value="">选择已收藏神祇</option>{owned.map(g=><option key={g.id} value={g.id}>{g.zh} · {g.en}</option>)}</select></label><div className="mode-tabs">{modes.map((m,i)=><button className={mode===i?'active':''} onClick={()=>{setMode(i);setResult('')}} key={m[0]}>{m[0]}<small>{m[1]}</small></button>)}</div><button className="fight" onClick={fight} disabled={owned.length<2}>开始试炼</button>{owned.length<2&&<small className="arena-hint">至少收藏两位神祇才能开始</small>}{result&&<p className="battle-result">{result}</p>}</div></section><section className="collection-heading"><div><span>全部神祇</span><h2>点击卡牌，加入收藏</h2></div><button onClick={()=>{setSaved([]);localStorage.removeItem('deity-collection')}}>清空收藏</button></section><section className="deity-deck">{gods.map(g=><article className={`deity-card ${saved.includes(g.id)?'owned':''}`} key={g.id}><button className="card-portrait" onClick={()=>toggle(g.id)} aria-label={`${saved.includes(g.id)?'取消收藏':'收藏'}${g.zh}`}><img src={`/deities/${g.id}.png`} alt={`${g.zh}传统艺术形象`}/><span>{saved.includes(g.id)?'✓ 已收藏':'＋ 收藏'}</span></button><div className="card-name"><em>{g.gender}</em><h3>{g.zh}</h3><b>{g.en}</b><small>{g.indic}</small><p>{g.role}</p></div><div className="stats">{modes.map((m,i)=><div key={m[0]}><span>{m[0]}</span><i><u style={{width:`${g.stats[i]}%`}}/></i><b>{g.stats[i]}</b></div>)}</div></article>)}</section></main>
}
