'use client';
import { useState } from 'react';
type D={id:string;name:string;dev:string;roman:string;group:string;title:string;role:string;signs:string;mount:string;region:string;festival:string;story:string;color:string};
const gods:D[]=[
['shiva','湿婆','शिव','Śiva','湿婆传统','转化与瑜伽之主','掌管转化、苦行、瑜伽、时间与舞蹈。毁灭不是终点，而是为新生腾出空间。','第三眼、三叉戟、新月、蓝喉、盘发中的恒河','南迪神牛','泛印度；瓦拉纳西、喜马拉雅与南印度影响尤深','大湿婆夜','搅乳海时致命毒液先涌出。湿婆为拯救众生将毒饮下，帕尔瓦蒂扼住他的喉咙，毒停留于颈部，使他获得“青颈者”之名。','#7898b2'],
['vishnu','毗湿奴','विष्णु','Viṣṇu','毗湿奴传统','宇宙秩序的守护者','守护正法与宇宙平衡；世界失序时，他以不同化身降世。','法螺、妙见神轮、莲花、权杖、蓝色皮肤','迦楼罗金翅鸟','泛印度；奥迪沙、泰米尔纳德、安得拉圣地众多','毗湿奴相关节期','传说他安卧于宇宙之蛇舍沙之上；正法衰落时，便以鱼、龟、野猪、罗摩、黑天等化身进入时间之流，重新校准世界。','#4a88a5'],
['brahma','梵天','ब्रह्मा','Brahmā','宇宙职能','创造与知识之神','三相神中的创造职能。须注意：梵天是神祇，并不等同于终极实在“梵”。','四张脸、四部吠陀、念珠、水罐','天鹅／雁','专门神庙较少；拉贾斯坦普什卡最著名','普什卡相关祭祀','莲花从毗湿奴的肚脐生出，梵天坐于花上开始创造。四张脸望向四方，也象征四部吠陀与遍观世界的知识。','#c88955'],
['devi','提毗／沙克蒂','देवी','Devī / Śakti','女神传统','神圣女性与宇宙能量','“提毗”意为女神，“沙克蒂”是能量；她是万物得以行动的原动力。','依形态而变；常见莲花、多臂、狮虎与神圣武器','依形态而变','泛印度；西孟加拉、阿萨姆与喜马拉雅女神圣地尤盛','九夜节、杜尔迦祭','《女神颂》中，众神的力量凝聚成杜尔迦。她骑狮迎战水牛魔王，显示神圣女性能独立恢复宇宙秩序。','#b74337'],
['ganesha','象头神','गणेश','Gaṇeśa','广泛敬奉','开端、智慧与除障之神','新事业、旅行、婚礼和学习开始前常先礼敬他；也掌管书写与辨识。','象头、大腹、断牙、甜球、绳索与刺棒','老鼠','泛印度；马哈拉施特拉尤盛，也广传东南亚','象头神节','帕尔瓦蒂创造男孩守门，湿婆不识而斩下其头。得知真相后，湿婆以象头使他复生，并赐予“祭祀前先受礼敬”的地位。','#d39a42'],
['lakshmi','吉祥天女','लक्ष्मी','Lakṣmī','女神传统','财富、福运与丰饶女神','象征财富、繁荣、美、王权与吉祥；财富也包含德行与丰足的生活。','红金衣袍、莲花、金币、两侧白象','猫头鹰','泛印度；家庭祭祀与商人社群中尤重要','排灯节','搅乳海时，她从莲花中升起并选择毗湿奴为伴侣。排灯节夜，人们点灯迎接她进入清洁、明亮而有秩序的家。','#c55753'],
['saraswati','辩才天女','सरस्वती','Sarasvatī','女神传统','知识、语言与艺术女神','守护学习、音乐、诗歌、记忆和清晰表达，常受学生与音乐家敬奉。','白衣、维纳琴、书、念珠、白莲','天鹅或孔雀','泛印度；东印度春季祭典尤鲜明','春五日节','她从古老河流女神演变为语言与知识的化身。琴象征思想与感受的调谐；天鹅象征辨别真伪的能力。','#d7c9a4'],
['durga','杜尔迦','दुर्गा','Durgā','女神传统','不可战胜的守护女神','保护正法、击败混乱与傲慢。多臂表示她能同时运用众神所赠的力量。','多臂、三叉戟、神轮、弓剑、红衣','狮或虎','西孟加拉、阿萨姆、奥迪沙及北印度','杜尔迦祭、九夜节','水牛魔王几乎无人能敌，诸神便将光芒合成杜尔迦。她与魔军大战九夜，在第十日击败水牛魔王。','#a83e31'],
['krishna','黑天','कृष्ण','Kṛṣṇa','毗湿奴传统','爱、喜悦与神圣导师','毗湿奴最受爱戴的化身之一：既是牧童、朋友，也是《薄伽梵歌》的导师。','蓝色皮肤、孔雀羽冠、长笛、黄衣','与牛群相伴','马图拉—温达文、古吉拉特、奥迪沙及全球奉爱传统','黑天诞辰节、洒红节','俱卢之野，阿周那不愿与亲族作战。黑天显现宇宙形，教导他不执着于结果地履行正法，以知识、行动与奉爱趋近神圣。','#366da5'],
['rama','罗摩','राम','Rāma','毗湿奴传统','正法与理想王者','毗湿奴化身，《罗摩衍那》中心人物，体现责任、节制、忠诚与理想王权。','弓箭、王冠、绿色或蓝色皮肤','常与悉多、罗什曼那、哈奴曼同现','北印度阿约提亚及泛印度；东南亚影响深远','罗摩诞辰节、十胜节','罗摩被放逐十四年，悉多被楞伽王罗波那掳走。他与哈奴曼及猴军结盟渡海，击败罗波那；归国灯火成为排灯节的重要叙事。','#527e61'],
['hanuman','哈奴曼','हनुमान','Hanumān','广泛敬奉','勇气、力量与奉爱的典范','保护者与疗愈者；他把巨大力量完全交给罗摩与正义使命。','猴面、金刚杵、山峰、胸中罗摩悉多','自身可飞行','泛印度；北印度与武艺传统中尤受敬奉','哈奴曼诞辰节','罗什曼那中箭危急，哈奴曼无法辨认救命药草，索性举起整座山带回战场，成为机敏、力量与忠诚的象征。','#b66d3b'],
['kali','迦梨','काली','Kālī','女神传统','时间、死亡与彻底解脱','她斩断自我幻象与束缚，外貌可怖却常被信徒称为慈母。','深色皮肤、伸舌、头颅花环、弯刀','常立于静卧的湿婆之上','西孟加拉、阿萨姆、奥迪沙及密续传统','迦梨祭','迦梨在战斗中势不可挡。湿婆卧于她脚下；她踩到伴侣后惊觉失控而伸舌停下，表现能量与意识的相互制衡。','#3f405d'],
['parvati','帕尔瓦蒂','पार्वती','Pārvatī','女神传统','爱、家庭与修行女神','湿婆的伴侣、象头神与室建陀之母；体现温柔、婚姻，也体现以坚定修行改变命运。','双臂、红色纱丽、莲花，常与湿婆同现','狮或虎','喜马拉雅与泛印度湿婆传统','提吉节、九夜节','她为赢得苦行者湿婆的认可，长期修行并展现坚定意志。两人的结合象征意识与能量不可分离。','#bd6e62'],
['radha','罗陀','राधा','Rādhā','毗湿奴传统','奉爱与灵魂渴望的化身','黑天最重要的伴侣之一；在奉爱传统中，她代表灵魂对神圣毫无保留的爱。','华丽纱丽、莲花，常与吹笛的黑天并立','无固定坐骑','温达文、北印度及高迪亚毗湿奴传统','罗陀诞辰节、洒红节','罗陀与黑天在温达文的相聚与分离，被诗人用来表达灵魂寻找神圣时的喜悦与深切渴望。','#cc6680'],
['sita','悉多','सीता','Sītā','毗湿奴传统','大地之女与坚韧王后','罗摩的伴侣，被视为吉祥天女的化身；象征忠诚、尊严、承受力与大地的丰饶。','纱丽、莲花，常与罗摩和哈奴曼同现','无固定坐骑','阿约提亚、米提拉与泛印度《罗摩衍那》传统','悉多诞辰节、排灯节','她从田垄中被发现，因此名为“犁沟”。被罗波那囚禁时仍拒绝屈服，最终回归母亲大地。','#b98e4b'],
['kartikeya','室建陀／穆鲁甘','स्कन्द','Skanda / Murugan','湿婆传统','战争、青春与胜利之神','湿婆与帕尔瓦蒂之子、象头神之兄弟；在南印度以穆鲁甘之名尤受爱戴。','神矛 Vel、六面、青年武士形象','孔雀','泰米尔纳德、喀拉拉、斯里兰卡与侨民社区','大宝森节、室建陀六日节','他由神圣火花诞生，统率天军击败阿修罗苏罗波陀曼；神矛象征洞穿无知的智慧。','#d47737'],
['jagannath','札格纳特','जगन्नाथ','Jagannātha','地域与化身','“世界之主”的黑天形态','奥迪沙重要神祇，通常被理解为黑天／毗湿奴的一种形态，与兄长大力罗摩和妹妹苏跋陀同祀。','圆形大眼、木质躯体、几何化面容','节庆巨型神车','奥迪沙普里及全球札格纳特神庙','普里战车节','每年神祇乘巨型神车离开内殿，与街道上的所有人相见；仪式强调神圣不只属于神庙深处。','#293f59'],
['surya','苏利耶／太阳神','सूर्य','Sūrya','吠陀诸神','太阳、光明与生命活力之神','带来光、时间、健康与见证一切的洞察力；太阳礼拜名称即源于他。','金色光轮、莲花、七匹马的战车','七马战车','奥迪沙科纳克、比哈尔及泛印度晨间礼拜','恰特节、桑克兰蒂节','他的战车每天由黎明驾驭者阿鲁纳驾驶，七匹马常被解释为一周七日或光的七色。','#d79b23'],
['indra','因陀罗','इन्द्र','Indra','吠陀诸神','雷雨、战争与天界之王','吠陀时代的重要神祇，掌管雷电、雨水和战士勇气；后期神话中为天界诸神之王。','金刚杵、雷电、王冠','白象爱罗婆多','泛印度经文与祭祀传统；尼泊尔因陀罗节尤盛','因陀罗节','巨蛇弗栗多阻塞河流，因陀罗挥动金刚杵将其击败，使水重新奔流，表现季风与解放受阻生命力。','#65799b'],
['agni','阿耆尼／火神','अग्नि','Agni','吠陀诸神','祭火与神人之间的使者','火焰把祭品带给诸神，也见证婚礼等仪式；因此连接家庭、祭坛与天界。','两张脸、火焰头发、七条舌、火焰光轮','公羊','泛印度吠陀仪式与家庭祭火','阿耆尼仪式遍及多种节庆','《梨俱吠陀》开篇首先呼唤阿耆尼。他既在天上为太阳、空中为闪电，也在地上成为祭火。','#d64d2e'],
['yama','阎摩','यम','Yama','吠陀诸神','死亡、审判与南方守护神','掌管亡者道路与行为后果；并非单纯恶魔，而是维持死亡秩序的王。','绳索、权杖、红衣、威严王冠','水牛','泛印度祖先祭祀；也是东亚“阎罗王”形象来源之一','阎摩灯节、兄妹节相关传说','他被称为第一位走完死亡道路的人，因而成为亡者之王；其记录官吉特拉古普塔审视众生行为。','#6e483f'],
['dhanvantari','檀凡陀利','धन्वन्तरि','Dhanvantari','地域与化身','阿育吠陀与疗愈之神','毗湿奴化身，被视为阿育吠陀医学的神圣奠基者，守护医者、健康与长寿。','四臂、甘露壶、草药、经书、法螺与神轮','无固定坐骑','泛印度医药传统与南印度神庙','檀凡陀利诞辰日','搅乳海时，他最后手捧不死甘露升出海面；这把医学、疗愈与恢复平衡联系在一起。','#55a083'],
['venkateswara','文卡泰斯瓦拉','वेंकटेश्वर','Veṅkaṭeśvara','地域与化身','蒂鲁帕蒂山上的毗湿奴','毗湿奴在南印度最重要的形态之一，也称巴拉吉；信徒向他祈求恩典与困境中的扶持。','高冠、额前白色 U 形印记、黑石神像、法螺神轮','迦楼罗','安得拉邦蒂鲁马拉—蒂鲁帕蒂','梵天节','传说他在黑暗时代住于七丘之上，接受众生供奉；蒂鲁马拉因此成为世界最繁忙的朝圣中心之一。','#59433d'],
['ayyappa','阿耶帕','അയ്യപ്പൻ','Ayyappa','地域与化身','纪律、守贞与和合之神','喀拉拉重要神祇，常被视为湿婆与毗湿奴女性形态摩希尼之子。','瑜伽坐姿、颈铃、束膝带、黑色服饰','虎','喀拉拉萨巴里马拉及南印度','曼陀罗—摩羯灯节','信徒前往萨巴里马拉前进行长期节制修行，并互称“斯瓦米”，强调克制、平等与共同朝圣。','#403c4e']
].map(a=>({id:a[0],name:a[1],dev:a[2],roman:a[3],group:a[4],title:a[5],role:a[6],signs:a[7],mount:a[8],region:a[9],festival:a[10],story:a[11],color:a[12]} as D));
const filters=['全部','湿婆传统','毗湿奴传统','女神传统','吠陀诸神','地域与化身','宇宙职能','广泛敬奉'];
const areas=[['北方 · 喜马拉雅与恒河','瓦拉纳西 · 阿约提亚 · 马图拉','湿婆 · 罗摩 · 黑天 · 哈奴曼'],['东方 · 三角洲与海岸','加尔各答 · 普里 · 卡马基亚','杜尔迦 · 迦梨 · 札格纳特 · 女神'],['西方 · 沙漠与商路','普什卡 · 德瓦尔卡 · 孟买','梵天 · 黑天 · 象头神 · 吉祥天女'],['南方 · 神庙之国','马杜赖 · 蒂鲁帕蒂 · 奇丹巴拉姆','湿婆 · 毗湿奴 · 米纳克希 · 室建陀']];
const portraitMap:Record<string,[string,number]>=Object.fromEntries([
  ...['shiva','vishnu','brahma','devi','ganesha','lakshmi','saraswati','durga'].map((x,i)=>[x,['a',i]]),
  ...['krishna','rama','hanuman','kali','parvati','radha','sita','kartikeya'].map((x,i)=>[x,['b',i]]),
  ...['jagannath','surya','indra','agni','yama','dhanvantari','venkateswara','ayyappa'].map((x,i)=>[x,['c',i]])
]) as Record<string,[string,number]>;
const faceStyle=(id:string)=>({backgroundImage:`url(/deities/${id}.png)`,backgroundPosition:'center 18%'} as React.CSSProperties);
const femaleIds=new Set(['devi','lakshmi','saraswati','durga','kali','parvati','radha','sita']);
const genderOf=(id:string)=>femaleIds.has(id)?'女神':'男神';
export default function Home(){const[chosen,setChosen]=useState<D|null>(null),[menu,setMenu]=useState(false);const node=(id:string,relation?:string)=>{const d=gods.find(x=>x.id===id)!;const gender=genderOf(id);return <button className="tree-node" onClick={()=>setChosen(d)} style={{'--accent':d.color} as React.CSSProperties}><i className="deity-face" style={faceStyle(id)}/><em className={`gender-badge ${gender==='女神'?'female':'male'}`}>{gender}</em>{relation&&<span>{relation}</span>}<b>{d.name}</b><small className="node-english">{d.roman}</small><small className="node-indic">{d.dev}</small></button>};return <main>
<nav className="topnav"><a className="brand" href="#top"><span className="brand-mark">ॐ</span><span>天竺神谱</span></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="打开导航">☰</button><div className={menu?'navlinks open':'navlinks'}><a href="#cosmos">世界观</a><a href="#deities">层级神谱</a><a href="/relations">神际关系 ↗</a><a href="#stories">故事</a><a href="#regions">地域</a></div></nav>
<section className="hero" id="top"><img src="/deities-cosmos.png" alt="印度教主要神祇艺术群像"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">印度教神祇 · 故事 · 象征 · 地域</p><h1>众神之中，<br/><em>看见同一个宇宙</em></h1><p>从创造、守护到转化，从史诗中的英雄到村落里的守护神——沿着故事，认识一套仍在呼吸的神圣传统。</p><a className="primary" href="#cosmos">开启神谱 <span>↓</span></a></div><p className="art-note">艺术化群像 · 形象依据传统标识创作</p></section>
<section className="cosmos" id="cosmos"><div className="section-kicker">01 · 先理解一个关键</div><div className="cosmos-grid"><h2>这不是一座<br/>固定的“<i>神仙阶梯</i>”</h2><div className="cosmos-text"><p>印度教没有一张被所有传统共同承认的单一神祇排行榜。不同教派会把<strong>湿婆、毗湿奴或女神</strong>视为最高实在的显现；许多神祇也互为化身、面相或亲属。</p><p>这里从宇宙职能到广泛敬奉的神祇纵向展开，帮助阅读，而不暗示谁高谁低。</p></div></div><div className="trimurti"><div><span>创造</span><b>梵天</b><small>Brahmā</small></div><i>✦</i><div><span>守护</span><b>毗湿奴</b><small>Viṣṇu</small></div><i>✦</i><div><span>转化</span><b>湿婆</b><small>Śiva</small></div></div></section>
<section className="genealogy" id="deities"><div className="tree-heading"><div><p className="section-kicker">02 · 神祇关系神谱 · 点击名字查看档案</p><h2>从最高实在，<br/>到主神、化身与家族</h2></div><div className="legend"><span><i className="line-solid"/>化身／形态</span><span><i className="line-double"/>伴侣</span><span><i className="line-dot"/>子女／奉献关系</span></div></div><div className="tree-scroll"><div className="tree">
  <div className="absolute-root"><span>终极实在 · 超越人格形象</span><b>梵 · Brahman</b><small>不同传统以不同主神理解它</small></div>
  <div className="root-stem"/><div className="tradition-rail"/>
  <div className="tree-columns">
    <section className="tree-branch shaiva"><header><span>湿婆传统 · Śaiva</span></header><div className="divine-couple">{node('shiva')}{node('parvati')}</div><div className="children-row">{node('ganesha','子')}{node('kartikeya','子')}</div><div className="desc-row">{node('ayyappa','湿婆 × 摩希尼之子')}</div></section>
    <section className="tree-branch vaishnava"><header><span>毗湿奴传统 · Vaiṣṇava</span></header><div className="divine-couple">{node('vishnu')}{node('lakshmi')}</div><div className="avatar-label">主要化身、伴侣与地域形态</div><div className="couple-families"><div className="family-pair"><span>罗摩传统</span><div>{node('rama','化身')}{node('sita','伴侣')}</div><aside>{node('hanuman','奉献者')}</aside></div><div className="family-pair"><span>黑天传统</span><div>{node('krishna','化身')}{node('radha','伴侣')}</div><aside>{node('jagannath','地域形态')}</aside></div></div><div className="standalone-avatars">{node('venkateswara','毗湿奴形态')}{node('dhanvantari','毗湿奴化身')}</div></section>
    <section className="tree-branch shakta"><header><span>女神传统 · Śākta</span>{node('devi')}</header><div className="avatar-label">同一神圣女性的主要形态</div><div className="goddess-row">{node('durga','战斗形态')}{node('kali','时间／毁灭')}{node('parvati','家庭／修行')}{node('lakshmi','丰饶／财富')}{node('saraswati','知识／艺术')}</div></section>
  </div>
  <div className="secondary-tier"><div className="secondary-title"><span>宇宙职能与古老吠陀诸神</span><small>重要，但通常不视为上述主神的“后代”</small></div><div className="secondary-nodes">{node('brahma','创造职能')}{node('surya','太阳')}{node('indra','雷雨／天界王')}{node('agni','祭火')}{node('yama','死亡秩序')}</div></div>
</div></div><p className="tree-note">性别标签表示本档案展示的主要人格形态。神圣本体常被理解为超越人类性别；湿婆有男女合一的半女神形态，毗湿奴也有女性化身摩希尼。关系会因经文、地区与教派而异。</p><a className="relations-cta" href="/relations"><span>打开独立关系地图</span><b>悬停在线上，阅读神与神之间的故事 →</b></a></section>
<section className="stories" id="stories"><div className="story-title"><p className="section-kicker">03 · 故事不是装饰</p><h2>神话把哲学<br/>变成<i>可以记住的画面</i></h2></div><div className="story-list">{gods.slice(0,5).map((d,i)=><button key={d.id} onClick={()=>setChosen(d)}><span>0{i+1}</span><div><b>{d.story.split('。')[0]}。</b><small>{d.name} · {d.title}</small></div><i>→</i></button>)}</div></section>
<section className="regions" id="regions"><div className="region-intro"><p className="section-kicker">04 · 信仰地理</p><h2>同一位神，<br/>在不同土地上有不同的亲近方式</h2><p>“分布”不是固定边界。泛印度神祇遍及各地，但圣城、方言传统与节庆会形成鲜明重心。</p></div><div className="region-grid">{areas.map((a,i)=><article key={a[0]}><span>0{i+1}</span><h3>{a[0]}</h3><b>{a[1]}</b><p>重要信仰重心与朝圣地带</p><small>{a[2]}</small></article>)}</div></section>
<section className="note"><span>ॐ</span><p>神像不是“照片式肖像”。颜色、多臂、坐骑和武器是传达能力与品格的视觉符号；不同地区与时代的画法可以不同。</p></section><footer><a className="brand" href="#top"><span className="brand-mark">ॐ</span><span>天竺神谱</span></a><p>为中文读者制作的入门神谱 · 尊重印度教内部多元传统</p><a href="#top">回到顶部 ↑</a></footer>
{chosen&&<div className="modal-backdrop" onClick={()=>setChosen(null)}><article className="modal" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true" style={{'--accent':chosen.color} as React.CSSProperties}><button className="close" onClick={()=>setChosen(null)}>×</button><div className="modal-top"><i className="modal-portrait" style={faceStyle(chosen.id)}/><div><p className="modal-indic">印度文字 · {chosen.dev}</p><p className="modal-english">English · {chosen.roman}</p><div className={`modal-gender ${genderOf(chosen.id)==='女神'?'female':'male'}`}>{genderOf(chosen.id)} · 主要人格形态</div><h2>{chosen.name}</h2><h3>{chosen.title}</h3></div></div><p className="lead">{chosen.role}</p><div className="facts"><div><span>性别／神圣形态</span><b>{genderOf(chosen.id)}（此档案展示的主要形态；神圣本体可能超越性别）</b></div><div><span>如何辨认</span><b>{chosen.signs}</b></div><div><span>坐骑／伴随</span><b>{chosen.mount}</b></div><div><span>主要信仰重心</span><b>{chosen.region}</b></div><div><span>重要节庆</span><b>{chosen.festival}</b></div></div><div className="modal-story"><span>经典故事</span><p>{chosen.story}</p></div></article></div>}</main>}
